# Generated by Django 6.0.3 on 2026-03-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_notes_created_notes_text_alter_notes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
