# Generated by Django 6.0.3 on 2026-03-06 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_notes_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
