# Generated by Django 6.0.1 on 2026-03-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
