# Generated by Django 6.0.3 on 2026-03-09 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_notes_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notes',
            table='note',
        ),
    ]
