# Generated by Django 6.0.3 on 2026-03-09 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_notes_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterModelTable(
            name='notes',
            table='notes',
        ),
    ]
